// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeRQAr4WWKMd9fspf2WIlax1EDO_0KXeY',
    appId: '1:311818244012:web:7ed257095303b210727409',
    messagingSenderId: '311818244012',
    projectId: 'dental-app-2026-new',
    authDomain: 'dental-app-2026-new.firebaseapp.com',
    storageBucket: 'dental-app-2026-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_kaHZasDGZSalq5duJHDwDpxIGfDUQw',
    appId: '1:311818244012:android:8ea96c1cb56a47dd727409',
    messagingSenderId: '311818244012',
    projectId: 'dental-app-2026-new',
    storageBucket: 'dental-app-2026-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMpgwr368FayFb_8wNG83EYnrXIKQumOM',
    appId: '1:311818244012:ios:9377aabeed1605d8727409',
    messagingSenderId: '311818244012',
    projectId: 'dental-app-2026-new',
    storageBucket: 'dental-app-2026-new.firebasestorage.app',
    iosBundleId: 'com.example.dentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMpgwr368FayFb_8wNG83EYnrXIKQumOM',
    appId: '1:311818244012:ios:9377aabeed1605d8727409',
    messagingSenderId: '311818244012',
    projectId: 'dental-app-2026-new',
    storageBucket: 'dental-app-2026-new.firebasestorage.app',
    iosBundleId: 'com.example.dentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeRQAr4WWKMd9fspf2WIlax1EDO_0KXeY',
    appId: '1:311818244012:web:18eac2169a9670c3727409',
    messagingSenderId: '311818244012',
    projectId: 'dental-app-2026-new',
    authDomain: 'dental-app-2026-new.firebaseapp.com',
    storageBucket: 'dental-app-2026-new.firebasestorage.app',
  );
}
